import os
import argparse
from Crypto.Util import number
from Crypto.PublicKey import RSA

def generate_rsa_keys_from_trng(trng_file_path, key_size=2048):
    if key_size % 2 != 0:
        print("Error: Key size must be an even number.")
        return None, None


    prime_bit_length = key_size // 2

    try:

        with open(trng_file_path, 'rb') as f:
            random_data_buffer = f.read()
        print(f"Read {len(random_data_buffer)} bytes from TRNG file: '{trng_file_path}'")


        current_offset = 0

        def trng_rand_func(num_bytes):
            nonlocal current_offset, random_data_buffer
            

            if current_offset + num_bytes > len(random_data_buffer):
                raise ValueError(f"Ran out of random data in the TRNG buffer. "
                                 f"Needed {num_bytes} bytes, but only {len(random_data_buffer) - current_offset} left.")
            

            extracted_bytes = random_data_buffer[current_offset : current_offset + num_bytes]

            current_offset += num_bytes
            return extracted_bytes

        e = 65537

        print(f"\nGenerating {key_size}-bit RSA keys...")
        print(f"Looking for two {prime_bit_length}-bit primes (p and q)...")

        try:

            p = number.getPrime(prime_bit_length, randfunc=trng_rand_func)
            print(f"Found prime 'p' with bit length: {p.bit_length()}")


            while True:
                q = number.getPrime(prime_bit_length, randfunc=trng_rand_func)
                if q != p:
                    print(f"Found prime 'q' with bit length: {q.bit_length()}")
                    break
                else:
                    print("Generated q was identical to p, trying again...")

        except ValueError as ve:
            print(f"ERROR: Could not generate primes from TRNG data: {ve}")
            return None, None
        
        n = p * q
        phi = (p - 1) * (q - 1)
        
        if number.GCD(e, phi) != 1:
            print(f"ERROR: Public exponent 'e' ({e}) is not coprime with phi.")
            return None, None

        d = number.inverse(e, phi)
        
        key_params = (n, e, d, p, q)
        key = RSA.construct(key_params)

        public_key = key.publickey()

        print("\nRSA Key Generation Complete!")
        print(f"Key Size: {key_size} bits")
        print(f"Public Exponent (e): {e}")

        return key, public_key

    except FileNotFoundError:
        print(f"ERROR: TRNG file not found at '{trng_file_path}'")
        return None, None
    except Exception as e:
        print(f"ERROR: An unexpected error occurred during key generation: {e}")
        return None, None

def main():
    parser = argparse.ArgumentParser(
        description="Generate RSA keys using random data from a TRNG binary file."
    )
    parser.add_argument(
        "trng_file",
        type=str,
        help="Path to the binary file generated by your TRNG (e.g., a file from a hardware TRNG)."
    )
    parser.add_argument(
        "--key_size",
        type=int,
        default=2048,
        choices=[1024, 2048, 3072, 4096],
        help="Desired RSA key size in bits (default: 2048)."
    )
    parser.add_argument(
        "--output_private",
        type=str,
        default="private_key.pem",
        help="Output file name for the private key (default: private_key.pem)."
    )
    parser.add_argument(
        "--output_public",
        type=str,
        default="public_key.pem",
        help="Output file name for the public key (default: public_key.pem)."
    )

    args = parser.parse_args()

    private_key, public_key = generate_rsa_keys_from_trng(args.trng_file, args.key_size)

    if private_key and public_key:
        try:
            with open(args.output_private, 'wb') as f:
                f.write(private_key.export_key('PEM'))
            print(f"Private key saved to {args.output_private}")

            with open(args.output_public, 'wb') as f:
                f.write(public_key.export_key('PEM'))
            print(f"Public key saved to {args.output_public}")
        except Exception as e:
            print(f"Error saving keys: {e}")
    else:
        print("RSA key generation process failed.")

if __name__ == "__main__":
    main()